// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganicShopBackend.Data;

#nullable disable

namespace OrganicShopBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250201155431_RemoveReviewsAndMetadata")]
    partial class RemoveReviewsAndMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrganicShopBackend.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("ReturnPolicy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingInformation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WarrantyInformation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.",
                            DiscountPercentage = 4.05m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Potatoes/1.png\"]",
                            MinimumOrderQuantity = 29,
                            Price = 45m,
                            QuantityInStock = 8,
                            Rating = 3.8199999999999998,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "W4NOBW45",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Potatoes/thumbnail.png",
                            Title = "Potatoes",
                            WarrantyInformation = "5 year warranty",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 2,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.",
                            DiscountPercentage = 17.89m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/1.png\"]",
                            MinimumOrderQuantity = 40,
                            Price = 50m,
                            QuantityInStock = 86,
                            Rating = 4.0800000000000001,
                            ReturnPolicy = "60 days return policy",
                            ShippingInformation = "Ships in 2 weeks",
                            Sku = "TAF870KJ",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/thumbnail.png",
                            Title = "Red Onions",
                            WarrantyInformation = "Lifetime warranty",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 3,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
                            DiscountPercentage = 11.44m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png\"]",
                            MinimumOrderQuantity = 7,
                            Price = 30m,
                            QuantityInStock = 22,
                            Rating = 4.71,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships overnight",
                            Sku = "6KGF2K6Z",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png",
                            Title = "Cucumber",
                            WarrantyInformation = "5 year warranty",
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = 4,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh broccoli, packed with vitamins, perfect for healthy meals and salads.",
                            DiscountPercentage = 12.5m,
                            Images = "[\"https://pixabay.com/get/g1b17eba27df6f4f681f4bb1e9ae2102e2e81756e64dc7723a66ca573577f243fb9df0ab1cd83fd529c9535a6f34d6dc08ebe0439c2e2235d7aa2a085f233ab3c_1280.png\"]",
                            MinimumOrderQuantity = 5,
                            Price = 60m,
                            QuantityInStock = 20,
                            Rating = 4.5,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0Y4NORN2",
                            Tags = "[\"greens\",\"healthy\",\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Broccoli/thumbnail.png",
                            Title = "Broccoli",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 5,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh and juicy tomatoes, perfect for salads, sauces, and cooking.",
                            DiscountPercentage = 15.0m,
                            Images = "[\"https://pixabay.com/get/g3c064f77e6790ec8d35b90cae5f245790c9bcb61588e055cc39f91d53a2e6aa2a0eca0cdfea5674c2d92b96f107fc037a46e7552a1d64c77e84ebaeb77a49ca7_1280.png\"]",
                            MinimumOrderQuantity = 10,
                            Price = 90m,
                            QuantityInStock = 50,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0T3M0T0",
                            Tags = "[\"fresh\",\"vegetables\",\"rich in vitamins\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Tomato/thumbnail.png",
                            Title = "Tomato",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 6,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Crunchy and sweet carrots, rich in beta-carotene, ideal for snacks and cooking.",
                            DiscountPercentage = 5.0m,
                            Images = "[\"https://pixabay.com/get/g713b394cac9b414df164d361727e3efd2c02e91ba69ce979f2b3de1f196ea6458edd2c85a9d69ebd03c01f480eceabee2e0c28d45705c6113e1dde2697da991d_1280.jpg\"]",
                            MinimumOrderQuantity = 5,
                            Price = 50m,
                            QuantityInStock = 40,
                            Rating = 4.7999999999999998,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0C4R0T0",
                            Tags = "[\"snack\",\"healthy\",\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Carrot/thumbnail.png",
                            Title = "Carrot",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 7,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Fresh and nutritious milk, a staple for various recipes and daily consumption.",
                            DiscountPercentage = 15.09m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Milk/1.png\"]",
                            MinimumOrderQuantity = 41,
                            Price = 35m,
                            QuantityInStock = 57,
                            Rating = 3.1400000000000001,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1 month",
                            Sku = "VOZKMF40",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Milk/thumbnail.png",
                            Title = "Milk",
                            WarrantyInformation = "6 months warranty",
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = 8,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Pure and clarified butter, perfect for cooking and traditional dishes.",
                            DiscountPercentage = 12.5m,
                            Images = "[\"https://pixabay.com/get/gb796cbed853e0edb1ee5fcd8ae9c0ddd4b6652f9bce82f7c0ab829b09c340c6f67940709695379bfe59f64703d3886c47d418f83ccb097cc27a13179e463eca6_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 400m,
                            QuantityInStock = 40,
                            Rating = 4.7000000000000002,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "GH3E5E",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Ghee/thumbnail.png",
                            Title = "Ghee",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = 9,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Rich and creamy butter, perfect for spreading or cooking.",
                            DiscountPercentage = 5.0m,
                            Images = "[\"https://pixabay.com/get/g0fe29c8175f0a328a0063543a59b8ed05969958ee207305345f77722466c21566b99686b2ae94838653e8d978208e83e7a1f0545384a2272e5f78c43b83e317b_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 270m,
                            QuantityInStock = 25,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "BU8T7E",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Butter/thumbnail.png",
                            Title = "Butter",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 10,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Delicious and creamy cheese, perfect for sandwiches and pizzas.",
                            DiscountPercentage = 7.5m,
                            Images = "[\"https://pixabay.com/get/g58d541b341f4855eca50fc2fd226a42905d8362edd911572e5a6cec58c87fe97973963afa2789fa56b84882f3609254305330af9edf16ce5d9a05c071d175434_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 300m,
                            QuantityInStock = 20,
                            Rating = 4.9000000000000004,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "CH4E3S",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Cheese/thumbnail.png",
                            Title = "Cheese",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 11,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Creamy and tangy yogurt, a great addition to smoothies and desserts.",
                            DiscountPercentage = 10.0m,
                            Images = "[\"https://pixabay.com/get/g545d9d935daf898002d64100c46d0f8a63b64773a4b29c2b127bb36d55911623ec678b351909db690a4b6ccb141c5c0cfaacea4d47e43b0cc4d3aa18095c049c_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 75m,
                            QuantityInStock = 60,
                            Rating = 4.2999999999999998,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "YO3G5T",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Yogurt/thumbnail.png",
                            Title = "Yogurt",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = 12,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.",
                            DiscountPercentage = 4.05m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Potatoes/1.png\"]",
                            MinimumOrderQuantity = 29,
                            Price = 45m,
                            QuantityInStock = 8,
                            Rating = 3.8199999999999998,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "W4NOBW45",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Potatoes/thumbnail.png",
                            Title = "Potatoes",
                            WarrantyInformation = "5 year warranty",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 13,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.",
                            DiscountPercentage = 17.89m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/1.png\"]",
                            MinimumOrderQuantity = 40,
                            Price = 50m,
                            QuantityInStock = 86,
                            Rating = 4.0800000000000001,
                            ReturnPolicy = "60 days return policy",
                            ShippingInformation = "Ships in 2 weeks",
                            Sku = "TAF870KJ",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Red%20Onions/thumbnail.png",
                            Title = "Red Onions",
                            WarrantyInformation = "Lifetime warranty",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 14,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
                            DiscountPercentage = 11.44m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png\"]",
                            MinimumOrderQuantity = 7,
                            Price = 30m,
                            QuantityInStock = 22,
                            Rating = 4.71,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships overnight",
                            Sku = "6KGF2K6Z",
                            Tags = "[\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png",
                            Title = "Cucumber",
                            WarrantyInformation = "5 year warranty",
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = 15,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh broccoli, packed with vitamins, perfect for healthy meals and salads.",
                            DiscountPercentage = 12.5m,
                            Images = "[\"https://pixabay.com/get/g1b17eba27df6f4f681f4bb1e9ae2102e2e81756e64dc7723a66ca573577f243fb9df0ab1cd83fd529c9535a6f34d6dc08ebe0439c2e2235d7aa2a085f233ab3c_1280.png\"]",
                            MinimumOrderQuantity = 5,
                            Price = 60m,
                            QuantityInStock = 20,
                            Rating = 4.5,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0Y4NORN2",
                            Tags = "[\"greens\",\"healthy\",\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Broccoli/thumbnail.png",
                            Title = "Broccoli",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 16,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Fresh and juicy tomatoes, perfect for salads, sauces, and cooking.",
                            DiscountPercentage = 15.0m,
                            Images = "[\"https://pixabay.com/get/g3c064f77e6790ec8d35b90cae5f245790c9bcb61588e055cc39f91d53a2e6aa2a0eca0cdfea5674c2d92b96f107fc037a46e7552a1d64c77e84ebaeb77a49ca7_1280.png\"]",
                            MinimumOrderQuantity = 10,
                            Price = 90m,
                            QuantityInStock = 50,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0T3M0T0",
                            Tags = "[\"fresh\",\"vegetables\",\"rich in vitamins\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Tomato/thumbnail.png",
                            Title = "Tomato",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 17,
                            AvailabilityStatus = "In Stock",
                            Category = "vegetables",
                            Description = "Crunchy and sweet carrots, rich in beta-carotene, ideal for snacks and cooking.",
                            DiscountPercentage = 5.0m,
                            Images = "[\"https://pixabay.com/get/g713b394cac9b414df164d361727e3efd2c02e91ba69ce979f2b3de1f196ea6458edd2c85a9d69ebd03c01f480eceabee2e0c28d45705c6113e1dde2697da991d_1280.jpg\"]",
                            MinimumOrderQuantity = 5,
                            Price = 50m,
                            QuantityInStock = 40,
                            Rating = 4.7999999999999998,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1-2 business days",
                            Sku = "0C4R0T0",
                            Tags = "[\"snack\",\"healthy\",\"vegetables\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/vegetables/Carrot/thumbnail.png",
                            Title = "Carrot",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 18,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Fresh and nutritious milk, a staple for various recipes and daily consumption.",
                            DiscountPercentage = 15.09m,
                            Images = "[\"https://cdn.dummyjson.com/products/images/groceries/Milk/1.png\"]",
                            MinimumOrderQuantity = 41,
                            Price = 35m,
                            QuantityInStock = 57,
                            Rating = 3.1400000000000001,
                            ReturnPolicy = "7 days return policy",
                            ShippingInformation = "Ships in 1 month",
                            Sku = "VOZKMF40",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Milk/thumbnail.png",
                            Title = "Milk",
                            WarrantyInformation = "6 months warranty",
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = 19,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Pure and clarified butter, perfect for cooking and traditional dishes.",
                            DiscountPercentage = 12.5m,
                            Images = "[\"https://pixabay.com/get/gb796cbed853e0edb1ee5fcd8ae9c0ddd4b6652f9bce82f7c0ab829b09c340c6f67940709695379bfe59f64703d3886c47d418f83ccb097cc27a13179e463eca6_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 400m,
                            QuantityInStock = 40,
                            Rating = 4.7000000000000002,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "GH3E5E",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Ghee/thumbnail.png",
                            Title = "Ghee",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = 20,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Rich and creamy butter, perfect for spreading or cooking.",
                            DiscountPercentage = 5.0m,
                            Images = "[\"https://pixabay.com/get/g0fe29c8175f0a328a0063543a59b8ed05969958ee207305345f77722466c21566b99686b2ae94838653e8d978208e83e7a1f0545384a2272e5f78c43b83e317b_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 270m,
                            QuantityInStock = 25,
                            Rating = 4.5999999999999996,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "BU8T7E",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Butter/thumbnail.png",
                            Title = "Butter",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 250.0
                        },
                        new
                        {
                            ProductId = 21,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Delicious and creamy cheese, perfect for sandwiches and pizzas.",
                            DiscountPercentage = 7.5m,
                            Images = "[\"https://pixabay.com/get/g58d541b341f4855eca50fc2fd226a42905d8362edd911572e5a6cec58c87fe97973963afa2789fa56b84882f3609254305330af9edf16ce5d9a05c071d175434_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 300m,
                            QuantityInStock = 20,
                            Rating = 4.9000000000000004,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "CH4E3S",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Cheese/thumbnail.png",
                            Title = "Cheese",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = 22,
                            AvailabilityStatus = "In Stock",
                            Category = "groceries",
                            Description = "Creamy and tangy yogurt, a great addition to smoothies and desserts.",
                            DiscountPercentage = 10.0m,
                            Images = "[\"https://pixabay.com/get/g545d9d935daf898002d64100c46d0f8a63b64773a4b29c2b127bb36d55911623ec678b351909db690a4b6ccb141c5c0cfaacea4d47e43b0cc4d3aa18095c049c_1280.png\"]",
                            MinimumOrderQuantity = 1,
                            Price = 75m,
                            QuantityInStock = 60,
                            Rating = 4.2999999999999998,
                            ReturnPolicy = "30 days return policy",
                            ShippingInformation = "Ships in 1 week",
                            Sku = "YO3G5T",
                            Tags = "[\"dairy\"]",
                            Thumbnail = "https://cdn.dummyjson.com/products/images/groceries/Yogurt/thumbnail.png",
                            Title = "Yogurt",
                            WarrantyInformation = "No warranty applicable",
                            Weight = 100.0
                        });
                });

            modelBuilder.Entity("OrganicShopBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Admin Street",
                            Email = "saiakash200236@gmail.com",
                            Name = "Freshio",
                            PasswordHash = "$2a$11$cm01/YvKO0LMGMcvEMl4oeQux88qi8oyHg1x.ysseoZdbS/SIqRse",
                            PhoneNumber = "1234567890",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Cart", b =>
                {
                    b.HasOne("OrganicShopBackend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrganicShopBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Order", b =>
                {
                    b.HasOne("OrganicShopBackend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.OrderItem", b =>
                {
                    b.HasOne("OrganicShopBackend.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganicShopBackend.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OrganicShopBackend.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
